version: "3.8"

networks:
  quickpay-network:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: quick-pay-postgres
    environment:
      POSTGRES_DB: quick-pay
      POSTGRES_USER: dias
      POSTGRES_PASSWORD: qaraqurt
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dias -d quick-pay"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - quickpay-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quick-pay-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/quick-pay
      SPRING_DATASOURCE_USERNAME: dias
      SPRING_DATASOURCE_PASSWORD: qaraqurt
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: BhUEAX5kmmBCeHzXyZ1234567890secureKey
      JWT_EXPIRATION: 12h
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - quickpay-network

  metabase:
    image: metabase/metabase
    container_name: metabase
    ports:
      - "3000:3000"
    volumes:
      - metabase-data:/metabase-data
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    depends_on:
      - postgres
    networks:
      - quickpay-network

volumes:
  postgres-data:
  metabase-data:
